Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "app"
  config.vm.network "private_network", ip: "192.168.1.3"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 3333, host: 3333
  config.vm.provision "shell", path: "provision.sh"
  config.ssh.insert_key = false

end
