
Vagrant.configure("2") do |config|
 
  config.vm.box = "centos/7"
  config.vm.hostname = 'docker'
  config.vm.network "forwarded_port",guest:5173,host:5173
  config.vm.network "forwarded_port",guest:3333,host:3333
  config.vm.provision "shell", path: "provision.sh"
end


