version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: yarn dev --host
    ports:
      - "5173:5173"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3333:3333"
    environment:
      DATABASE_URL: mysql://root:1357.modanesi@host.docker.internal:3306/systemtask

